"""empty message

Revision ID: 127437f7af1f
Revises: 18d83588429f
Create Date: 2020-08-08 14:28:53.046079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127437f7af1f'
down_revision = '18d83588429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response__finalass__addr',
    sa.Column('EARF_Number', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Response_Time_Class', sa.String(length=300), nullable=False),
    sa.Column('Street_Name', sa.String(500), nullable=False),
    sa.Column('Suburb', sa.String(300), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.Column('FA_Code', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('EARF_Number')
    )
    op.create_index(op.f('ix_response__finalass__addr_FA_Code'), 'response__finalass__addr', ['FA_Code'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Lat'), 'response__finalass__addr', ['Lat'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Lon'), 'response__finalass__addr', ['Lon'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Response_Time_Class'), 'response__finalass__addr', ['Response_Time_Class'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Street_Name'), 'response__finalass__addr', ['Street_Name'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Suburb'), 'response__finalass__addr', ['Suburb'], unique=False)
    op.create_index(op.f('ix_response__finalass__addr_Year'), 'response__finalass__addr', ['Year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response__finalass__addr_Year'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_Suburb'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_Street_Name'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_Response_Time_Class'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_Lon'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_Lat'), table_name='response__finalass__addr')
    op.drop_index(op.f('ix_response__finalass__addr_FA_Code'), table_name='response__finalass__addr')
    op.drop_table('response__finalass__addr')
    # ### end Alembic commands ###
