"""empty message

Revision ID: 18d83588429f
Revises: 60a7dea13533
Create Date: 2020-08-08 12:14:48.238165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d83588429f'
down_revision = '60a7dea13533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime__response_FA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Response_Time_Class', sa.String(length=300), nullable=False),
    sa.Column('FA_Code', sa.String(length=64), nullable=False),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime__response_FA_Count'), 'overtime__response_FA', ['Count'], unique=False)
    op.create_index(op.f('ix_overtime__response_FA_FA_Code'), 'overtime__response_FA', ['FA_Code'], unique=False)
    op.create_index(op.f('ix_overtime__response_FA_Response_Time_Class'), 'overtime__response_FA', ['Response_Time_Class'], unique=False)
    op.create_table('response__time__count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Class', sa.String(length=300), nullable=False),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response__time__count_Class'), 'response__time__count', ['Class'], unique=False)
    op.create_index(op.f('ix_response__time__count_Count'), 'response__time__count', ['Count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response__time__count_Count'), table_name='response__time__count')
    op.drop_index(op.f('ix_response__time__count_Class'), table_name='response__time__count')
    op.drop_table('response__time__count')
    op.drop_index(op.f('ix_overtime__response_FA_Response_Time_Class'), table_name='overtime__response_FA')
    op.drop_index(op.f('ix_overtime__response_FA_FA_Code'), table_name='overtime__response_FA')
    op.drop_index(op.f('ix_overtime__response_FA_Count'), table_name='overtime__response_FA')
    op.drop_table('overtime__response_FA')
    # ### end Alembic commands ###
