"""empty message

Revision ID: 60a7dea13533
Revises: 
Create Date: 2020-08-04 15:54:08.184083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a7dea13533'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final__assessment__count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FA_Code', sa.String(length=64), nullable=False),
    sa.Column('FA_desc', sa.String(length=300), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final__assessment__count_Count'), 'final__assessment__count', ['Count'], unique=False)
    op.create_index(op.f('ix_final__assessment__count_FA_Code'), 'final__assessment__count', ['FA_Code'], unique=False)
    op.create_index(op.f('ix_final__assessment__count_FA_desc'), 'final__assessment__count', ['FA_desc'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_final__assessment__count_FA_desc'), table_name='final__assessment__count')
    op.drop_index(op.f('ix_final__assessment__count_FA_Code'), table_name='final__assessment__count')
    op.drop_index(op.f('ix_final__assessment__count_Count'), table_name='final__assessment__count')
    op.drop_table('final__assessment__count')
    # ### end Alembic commands ###
